service: waypoint-demo

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    dockerImage: public.ecr.aws/sam/build-python3.9:latest

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'
  region: us-east-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: GET
          authorizer:
            name: waypointc
            scopes:
              - waypoint/*
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:ap-south-1:026720776677:userpool/ap-south-1_wD3fO1mkQ


plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - '!__pycache__/**'
    - '!_node_modules/**'
    - '!venv/**'
