name: Waypoint Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Waypoint API deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing npm dependencies
        run: npm ci

      - name: Enforce Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.1'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Serverless Dev Deploy
        if: ${{ github.ref != 'refs/heads/develop' }}
        uses: serverless/github-action@v3.1
        with:
          args: -c "serverless plugin install --name serverless-python-requirements && serverless plugin install --name serverless-wsgi && serverless deploy --stage dev --verbose"
          entrypoint: /bin/sh

      - name: Serverless Prod Deploy
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: serverless/github-action@v3.1
        with:
          args: -c "serverless plugin install --name serverless-python-requirements && serverless plugin install --name serverless-wsgi && serverless deploy --stage prod --verbose"
          entrypoint: /bin/sh